# Generated by Django 3.2.3 on 2021-05-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wolf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wolf',
            name='title',
        ),
        migrations.AlterField(
            model_name='wolf',
            name='email',
            field=models.CharField(blank=True, max_length=100, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='wolf',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='wolf',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Second Name'),
        ),
    ]
