# Generated by Django 3.2.3 on 2021-05-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wolf', '0002_auto_20210519_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='wolf',
            name='amount',
            field=models.CharField(blank=True, max_length=30, verbose_name='amount'),
        ),
        migrations.AddField(
            model_name='wolf',
            name='date',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='wolf',
            name='transaction',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Transaction'),
        ),
        migrations.AlterField(
            model_name='wolf',
            name='email',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='email'),
        ),
    ]
