# Generated by Django 3.2.3 on 2021-05-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wolf', '0005_wolf_trans_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wolf',
            name='transaction',
            field=models.IntegerField(choices=[(1, 'income'), (2, 'withdrawal of funds')], verbose_name='Transaction'),
        ),
    ]
