# Generated by Django 3.2.3 on 2021-05-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wolf', '0006_alter_wolf_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wolf',
            name='Trans_from',
            field=models.CharField(blank=True, max_length=100, verbose_name='From / To whom'),
        ),
    ]
