# Generated by Django 3.2.3 on 2021-05-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wolf', '0007_alter_wolf_trans_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wolf',
            name='transaction',
            field=models.IntegerField(choices=[('income', 'Income'), ('withdrawal of funds', 'Withdrawal of funds')], verbose_name='Transaction'),
        ),
    ]
